/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as S3DemoRouteImport } from './routes/s3-demo'
import { Route as IndexRouteImport } from './routes/index'

const S3DemoRoute = S3DemoRouteImport.update({
  id: '/s3-demo',
  path: '/s3-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/s3-demo': typeof S3DemoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/s3-demo': typeof S3DemoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/s3-demo': typeof S3DemoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/s3-demo'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/s3-demo'
  id: '__root__' | '/' | '/s3-demo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  S3DemoRoute: typeof S3DemoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/s3-demo': {
      id: '/s3-demo'
      path: '/s3-demo'
      fullPath: '/s3-demo'
      preLoaderRoute: typeof S3DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  S3DemoRoute: S3DemoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
